# Uncomment this line to define a global platform for your project
 platform :ios, '10.0'

target 'Vision One' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vision One
  # added by Pouria
  #pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => ‘swift3’ 
  pod 'Google/Analytics'


  target 'Vision OneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Vision OneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
